### ISSUE TITLE
XMLFileFilter should ignore initial comments

### ISSUE THREAD

**Issue by DirkMahler** [jQAssistant/jqa-xml-plugin#4]
XMLFileFilter is used identify the JPA version of persistence.xml files but currently fails if the first element in the file is a comment, e.g. 

```
<?xml version="1.0" encoding="UTF-8"?>
<!--
Some comment
  -->
<persistence version="2.1" ..
```

**Comment by yrodiere** [comment]
@DirkMahler Hi!

We recently hit on this bug when we tried to use jqassistant on https://github.com/hibernate/hibernate-search. There doesn't seem to be a workaround except changing the XML files, which is not really an option in our case.

Do you think you will be able to release version 1.4 anytime soon?  That would be greatly appreciated.

**Comment by DirkMahler** [comment]
It's planned for beginning/mid of May, so hopefully not too much time to wait for you to... Do you have the chance to verify if the current 1.4.0-SNAPSHOT version works for you? It's available from the Sonatype OSS Snapshot repository (https://oss.sonatype.org/content/repositories/snapshots/).

**Comment by yrodiere** [comment]
> Do you have the chance to verify if the current 1.4.0-SNAPSHOT version works for you?

I just did, and it works like a charm :)

> It's planned for beginning/mid of May, so hopefully not too much time to wait for you to...

We'll wait, thanks!
